# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

In [0]:
from google.colab import files
uploaded = files.upload()

Saving iris.csv to iris.csv
Saving prices.csv to prices.csv


### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(35)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd
import numpy as np

In [0]:
from sklearn import datasets
iris = datasets.load_iris()


## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:

X = iris.data
y = iris.target
print (X)
print (Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
train_set, test_set, train_labels, test_labels = train_test_split(X, y, test_size=0.25, random_state=1)


In [0]:
train_set.shape


(112, 4)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
train_labels = tf.keras.utils.to_categorical(train_labels, num_classes=3)
test_labels = tf.keras.utils.to_categorical(test_labels, num_classes=3)


## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from sklearn.preprocessing import Normalizer
transformer = Normalizer()
train_set = transformer.fit_transform(train_set)

In [0]:
model = tf.keras.models.Sequential()


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', 
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
model.fit(train_set,train_labels,          
          validation_data=(test_set,test_labels),
          epochs=100)


Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 5ms/sample - loss: 1.1943 - accuracy: 0.3036 - val_loss: 2.1972 - val_accuracy: 0.4211
Epoch 2/100
112/112 [==============================] - 0s 149us/sample - loss: 1.1925 - accuracy: 0.3036 - val_loss: 2.1705 - val_accuracy: 0.4211
Epoch 3/100
112/112 [==============================] - 0s 155us/sample - loss: 1.1907 - accuracy: 0.3036 - val_loss: 2.1446 - val_accuracy: 0.4211
Epoch 4/100
112/112 [==============================] - 0s 158us/sample - loss: 1.1889 - accuracy: 0.3036 - val_loss: 2.1171 - val_accuracy: 0.4211
Epoch 5/100
112/112 [==============================] - 0s 231us/sample - loss: 1.1871 - accuracy: 0.3036 - val_loss: 2.0893 - val_accuracy: 0.4211
Epoch 6/100
112/112 [==============================] - 0s 160us/sample - loss: 1.1851 - accuracy: 0.3036 - val_loss: 2.0688 - val_accuracy: 0.4211
Epoch 7/100
112/112 [==============================] - 0s 185us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
model.input

<tf.Tensor 'dense_1_input:0' shape=(None, 4) dtype=float32>

In [0]:
input_data = np.expand_dims(test_set[0], axis=0)
print(input_data.shape)

(1, 4)


In [0]:
predicted = model.predict(input_data)
predicted

array([[0.11161622, 0.58860475, 0.29977903]], dtype=float32)

In [0]:

predicted[0]

array([0.11161622, 0.58860475, 0.29977903], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
test_labels[0]

array([1., 0., 0.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [5]:
# run this cell to upload file if you are using google colab
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive




already loaded on top

In [0]:
import os
os.chdir('/content/drive/My Drive/Colab Notebooks')

In [0]:
price_df = pd.read_csv("prices.csv")

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
from sklearn.preprocessing import Normalizer
import pandas as pd
import numpy as np

In [26]:
price_df.drop(['date','symbol'],axis=1,inplace=True)
price_df

open       close         low        high     volume
0       123.430000  125.839996  122.309998  126.250000  2163600.0
1       125.239998  119.980003  119.940002  125.540001  2386400.0
2       116.379997  114.949997  114.930000  119.739998  2489500.0
3       115.480003  116.620003  113.500000  117.440002  2006300.0
4       117.010002  114.970001  114.089996  117.330002  1408600.0
...            ...         ...         ...         ...        ...
851259  103.309998  103.199997  102.849998  103.930000   973800.0
851260   43.070000   43.040001   42.689999   43.310001  1938100.0
851261   53.639999   53.529999   53.270000   53.740002  1701200.0
851262   44.730000   45.450001   44.410000   45.590000  1380900.0
851263   54.200001   53.630001   53.389999   54.480000   705100.0

[851264 rows x 5 columns]

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [27]:
price_df.shape

(851264, 5)

In [0]:
price1_df = price_df.head(1000)

In [29]:
price1_df.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [33]:
price1_df['volume'] = price1_df['volume']/1000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [34]:
price1_df.head()

open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
from sklearn.model_selection import train_test_split
X = price1_df.drop(['volume'],axis=1)
Y = price1_df[['volume']]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=1)


In [0]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('float32')
y_test= y_test.astype('float32')


In [41]:
print(X_train.info())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 670 entries, 481 to 37
Data columns (total 4 columns):
open     670 non-null float32
close    670 non-null float32
low      670 non-null float32
high     670 non-null float32
dtypes: float32(4)
memory usage: 15.7 KB
None


In [42]:
print(X_test.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 330 entries, 507 to 563
Data columns (total 4 columns):
open     330 non-null float32
close    330 non-null float32
low      330 non-null float32
high     330 non-null float32
dtypes: float32(4)
memory usage: 7.7 KB
None


In [43]:
print(y_train.info())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 670 entries, 481 to 37
Data columns (total 1 columns):
volume    670 non-null float32
dtypes: float32(1)
memory usage: 7.9 KB
None


In [44]:
print(y_test.info())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 330 entries, 507 to 563
Data columns (total 1 columns):
volume    330 non-null float32
dtypes: float32(1)
memory usage: 3.9 KB
None


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_Scale = scaler.transform(X_train)

In [0]:
scaler.fit(X_test)
X_test_Scale = scaler.transform(X_test)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
import tensorflow as tf
tf.__version__
weight = tf.zeros(shape=(4,1))
bias = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, weight, bias):
    
    xw_matmul = tf.matmul(x, weight)
    y = tf.add(xw_matmul, bias)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    difference = y_actual - y_predicted
    square = tf.square(difference)
    average = tf.reduce_mean(square)
    
    return average

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, weight, bias, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([weight,bias])
        
        current_prediction = prediction(x, weight, bias)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[weight, bias])
    
    #Update Weights and Bias
    weight = weight - learning_rate*dw
    bias = bias - learning_rate*db
    
    return weight, bias

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [0]:
X_train_Scale = X_train_Scale.astype("float32")
X_test_Scale = X_test_Scale.astype("float32")


In [57]:
for i in range(100):
    weight, bias = train(X_train_Scale, np.array(y_train), weight, bias)
    print('Current Loss on iteration', i, loss(np.array(y_train), prediction(X_train_Scale, weight, bias)).numpy())

Current Loss on iteration 0 226.56677
Current Loss on iteration 1 224.858
Current Loss on iteration 2 223.27962
Current Loss on iteration 3 221.81683
Current Loss on iteration 4 220.45688
Current Loss on iteration 5 219.18886
Current Loss on iteration 6 218.00322
Current Loss on iteration 7 216.89178
Current Loss on iteration 8 215.84746
Current Loss on iteration 9 214.864
Current Loss on iteration 10 213.93604
Current Loss on iteration 11 213.05876
Current Loss on iteration 12 212.22803
Current Loss on iteration 13 211.44028
Current Loss on iteration 14 210.69217
Current Loss on iteration 15 209.98093
Current Loss on iteration 16 209.30382
Current Loss on iteration 17 208.65875
Current Loss on iteration 18 208.04352
Current Loss on iteration 19 207.45639
Current Loss on iteration 20 206.89561
Current Loss on iteration 21 206.35968
Current Loss on iteration 22 205.8472
Current Loss on iteration 23 205.35687
Current Loss on iteration 24 204.88763
Current Loss on iteration 25 204.43831
C

### Observe values of Weight
- Print the updated values

In [58]:
print('Weights:\n', weight.numpy())

Weights:
 [[-0.52333796]
 [-0.50654745]
 [-0.5065538 ]
 [-0.52056706]]


### Observe values of Bias
- Print the updated values

In [59]:
print('Bias:\n',bias.numpy())

Bias:
 [4.7871876]
